name: Docker CICD
on:
  push:
    branches:
      - backend
  pull_request:
    branches:
      - backend

env:
  CI: false
  env_backend: ${{secrets.ENV_BACKEND}}

defaults:
  run:
    working-directory: BackEnd

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    

    steps:
      - name: checkout backend branch
        uses: actions/checkout@v3
        with:
          ref: backend

      - name: create environment file
        run: |
          touch ./.env && echo "$env_backend" >> ./.env

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v2

      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build and push 
        uses: docker/build-push-action@v4
        if: github.event_name == 'push'
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: thespiritman/yantra-backend:backend

      - name: Build Docker image
        if: github.event_name == 'pull_request'
        run: docker build -t myimage:${{ github.sha }} -f ./Dockerfile .